### ISSUE TITLE
feat(jhh-api): jhhm-26 - integrate and stand up service

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/jhh-mono#26]
We are doing a few things in these changes:

1. "wring up" the parts of the application 
2. validating the requests to the `/pets` endpoint work
3. determining where to refactor and optimize the service and creating stories based on that discovery

## Acceptance Criteria
- The `jhh-api` service can be stood up in a local environment
- The `api/pets` endpoint can be called and returns a valid response from the database
- Any optimizations discovered during this work as recorded as tech debt stories

**Comment by wijohnst** [comment]
## `IJHHApp` Instantiation
First issue was not properly instantiation of the `JHHApp` object in `index.ts`. The solution was to pass in `express.Application` to the class's constructor. 

### `Object.defineProperty(this, 'router'` Error
After updating `index.ts` to include `express.Application` the refreshed server returned this on startup:

```
jhh-api:dev: [nodemon] starting `ts-node ./src/index.ts`
jhh-api:dev: Establishing connection to database... mongodb+srv://wijohnst:admin@johnston-home-hub-clust.36zs8ue.mongodb.net/?retryWrites=true&w=majority
jhh-api:dev: /Users/ISG2330/workspace/personal/jhh-mono/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:129
jhh-api:dev:   Object.defineProperty(this, 'router', {
jhh-api:dev:          ^
jhh-api:dev: TypeError: Cannot redefine property: router
jhh-api:dev:     at Function.defineProperty (<anonymous>)
jhh-api:dev:     at Function.defaultConfiguration (/Users/ISG2330/workspace/personal/jhh-mono/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:129:10)
jhh-api:dev:     at Function.init (/Users/ISG2330/workspace/personal/jhh-mono/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:69:8)
jhh-api:dev:     at JhhApp.initServer (/Users/ISG2330/workspace/personal/jhh-mono/apps/jhh-api/src/providers/jhh-app/jhh-app.ts:16:18)
jhh-api:dev:     at Object.<anonymous> (/Users/ISG2330/workspace/personal/jhh-mono/apps/jhh-api/src/index.ts:11:8)
jhh-api:dev:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
jhh-api:dev:     at Module.m._compile (/Users/ISG2330/workspace/personal/jhh-mono/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.5.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
jhh-api:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
jhh-api:dev:     at Object.require.extensions.<computed> [as .ts] (/Users/ISG2330/workspace/personal/jhh-mono/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.5.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12)
jhh-api:dev:     at Module.load (node:internal/modules/cjs/loader:1043:32)
jhh-api:dev: [nodemon] app crashed - waiting for file changes before starting...
^[^C
jhh-api:dev:  ELIFECYCLE  Command failed.
```

#### 👇 Troubleshooting 👆

##### Stack Trace
`index.ts` --> `jhhApp.initServer()` --> `IExpress.init()`
